'use client';

import { useMemo, useState } from 'react';
import { Card } from '@/components/Card';
import { Input } from '@/components/Input';
import { Button } from '@/components/Button';
import { useLanguage } from '@/contexts/LanguageContext';
import { ChevronDown, ChevronUp, Search, MessageCircle, BookOpen, Link as LinkIcon, AlertCircle } from 'lucide-react';

interface FAQItem {
  question: string;
  answer: string;
  category: 'Getting Started' | 'Deployment' | 'Accounts';
}

// Useful references
const LINKS = {
  gdpr32: 'https://gdpr.eu/article-32-security-of-processing/',
  gdpr25: 'https://gdpr.eu/article-25-data-protection-by-design/',
  gdpr35: 'https://gdpr.eu/article-35-data-protection-impact-assessment/',
  gdpr30: 'https://gdpr.eu/article-30-record-of-processing-activities/',
  gdprChapterV: 'https://gdpr.eu/chapter-5/',
  finDPA: 'https://www.finlex.fi/en/laki/kaannokset/2018/en20181050',
  aiAct: 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
  nis2: 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
  scc: 'https://commission.europa.eu/law/law-topic/data-protection/international-transfers-personal-data_en',
  iso27001: 'https://www.iso.org/isoiec-27001-information-security.html',
  copyrightFI: 'https://finlex.fi/en/laki/kaannokset/1961/en19610404',
  tradeSecrets: 'https://eur-lex.europa.eu/eli/dir/2016/943/oj',
  productLiability2024: 'https://eur-lex.europa.eu/eli/dir/2024/2853/oj',
  dualUse: 'https://eur-lex.europa.eu/eli/reg/2021/821/oj',
  tfeu101: 'https://eur-lex.europa.eu/EN/legal-content/summary/restriction-of-competition-agreements-article-101-tfeu.html',
  tfeu102: 'https://eur-lex.europa.eu/EN/legal-content/summary/abuse-of-dominant-position-article-102-tfeu.html',
  enisaAccess: 'https://www.enisa.europa.eu/topics/identity-and-trust',
  oidc: 'https://openid.net/connect/',
  saml: 'https://wiki.oasis-open.org/security/FrontPage',
  greenDigital: 'https://digital-strategy.ec.europa.eu/en/library/proposal-council-recommendation-green-transition-and-digital-transformation-eu-education-and-training',
};

const SECTIONS: { title: string; items: FAQItem[] }[] = [
  {
    title: 'Data Security and Confidentiality',
    items: [
      {
        question: 'How is sensitive business data protected once uploaded into the sandbox?',
        answer: `All uploaded data will be protected under GDPR Article 32 (security of processing) and the Finnish Data Protection Act (1050/2018). Data will be encrypted in transit (TLS 1.3) and at rest (AES-256), stored only in EU/EEA data centres, and isolated per tenant. We will apply data‑protection‑by‑design (GDPR Art. 25) and will follow ISO 27001 and zero‑trust security frameworks.\n\nLinks: [GDPR Art. 32](${LINKS.gdpr32}), [GDPR Art. 25](${LINKS.gdpr25}), [Finnish DPA](${LINKS.finDPA}), [ISO 27001](${LINKS.iso27001}).`,
        category: 'Getting Started'
      },
      {
        question: 'Are encryption and access controls strong enough to prevent leaks between collaborators?',
        answer: `Yes. We will enforce role‑based access control (RBAC), multi‑factor authentication, and strict tenant isolation, aligning with GDPR Art. 32(1) and the NIS 2 Directive. Encryption keys will support BYOK/CMK so only the data owner will be able to decrypt content.\n\nLinks: [GDPR Art. 32](${LINKS.gdpr32}), [NIS 2](${LINKS.nis2}).`,
        category: 'Deployment'
      },
      {
        question: 'Where is the data physically stored, and how do you ensure GDPR or sector-specific compliance?',
        answer: `Data will be stored exclusively in EU/EEA regions (primarily Finland) to comply with GDPR Chapter V on international transfers. No personal or regulated data will leave the EEA without an adequacy decision or Standard Contractual Clauses (SCCs). Sector‑specific rules (e.g. healthcare or finance) will be handled through isolated nodes and documented DPIAs (GDPR Art. 35).\n\nLinks: [GDPR Chapter V](${LINKS.gdprChapterV}), [SCCs](${LINKS.scc}), [GDPR Art. 35](${LINKS.gdpr35}).`,
        category: 'Deployment'
      }
    ]
  },
  {
    title: 'Intellectual Property (IP) Ownership',
    items: [
      {
        question: 'Who owns the outputs generated by the LLM when multiple organizations contribute data or prompts?',
        answer: `Each participant will retain ownership of its inputs (data, prompts, models). Outputs and co‑created models will follow the collaboration agreement, consistent with the Finnish Copyright Act (404/1961) and the EU Trade Secrets Directive 2016/943. Unless otherwise agreed, jointly created results will be jointly owned.\n\nLinks: [Finnish Copyright Act](${LINKS.copyrightFI}), [EU Trade Secrets Directive](${LINKS.tradeSecrets}).`,
        category: 'Getting Started'
      },
      {
        question: 'How is proprietary know-how protected during collaboration?',
        answer: `Proprietary information will be safeguarded through technical segregation, confidentiality clauses, and data protection by design (GDPR Art. 25). Each project will run in an isolated workspace; no fine‑tuning or shared model merges will occur across projects. Logging and provenance features will prevent unintentional disclosure of trade secrets.\n\nLinks: [GDPR Art. 25](${LINKS.gdpr25}).`,
        category: 'Accounts'
      },
      {
        question: 'How are derivative models or works handled?',
        answer: `Derivative models will remain under contributors’ control, governed by explicit licence terms in the Consortium Agreement. The sandbox operator will not claim ownership or reuse rights. This approach will align with Finnish IP law and EU copyright principles on derivative works.`,
        category: 'Accounts'
      }
    ]
  },
  {
    title: 'Model Governance and Accountability',
    items: [
      {
        question: 'If the LLM produces incorrect, biased, or harmful outputs, who is responsible?',
        answer: `Responsibility will be allocated under GDPR Art. 26 (joint controllers) and each project’s contractual framework. The sandbox will maintain full traceability, version control, and audit logs, aligning with EU AI Act requirements such as risk management, logging, and human oversight.\n\nLinks: [AI Act overview](${LINKS.aiAct}).`,
        category: 'Getting Started'
      },
      {
        question: 'Can companies trace which prompts, datasets, or users produced a specific output?',
        answer: `Yes. Every model run will be cryptographically logged with user ID, timestamp, dataset hash, and model version. These immutable records will be exportable for independent audit or regulator review and will fulfil logging and traceability requirements in the AI Act.\n\nLinks: [AI Act overview](${LINKS.aiAct}).`,
        category: 'Deployment'
      },
      {
        question: 'How do you ensure explainability and trust in model outputs?',
        answer: `The sandbox will include documentation and interpretability tools. Each output will be tied to model version and training context, with optional human‑in‑the‑loop review points, supporting transparency and user‑information duties in the AI Act.\n\nLinks: [AI Act overview](${LINKS.aiAct}).`,
        category: 'Deployment'
      }
    ]
  },
  {
    title: 'Interoperability and Access Control',
    items: [
      {
        question: 'How is secure access managed when companies use different cloud or IT systems?',
        answer: `We will provide federated identity management via OpenID Connect or SAML 2.0, with multi‑factor authentication. Access rights will be limited by role‑based and attribute‑based controls, consistent with GDPR Art. 32(1)(b) and ENISA best practice for cross‑organization security.\n\nLinks: [OpenID Connect](${LINKS.oidc}), [SAML 2.0](${LINKS.saml}), [ENISA](${LINKS.enisaAccess}).`,
        category: 'Getting Started'
      },
      {
        question: 'Can collaborators accidentally gain access to each other’s internal systems?',
        answer: `No. The sandbox will use network segmentation, micro‑segmentation, and API gateways that enforce project boundaries. Data will never flow between tenants without explicit authorization, aligning with ISO 27001 Annex A.13 (network security controls).`,
        category: 'Deployment'
      },
      {
        question: 'How do you keep collaboration smooth without over‑exposing internal assets?',
        answer: `Shared projects will run in controlled “collab zones.” Partners will be able to share datasets or results via fine‑grained permissions while keeping core systems isolated. This approach will follow the purpose‑limitation principle (GDPR Art. 5(1)(b)).`,
        category: 'Accounts'
      }
    ]
  },
  {
    title: 'Compliance and Legal Risks',
    items: [
      {
        question: 'How do you ensure overall compliance with GDPR and the EU AI Act?',
        answer: `Compliance will be built‑in (“compliance by design”). We will conduct DPIAs (GDPR Art. 35) for high‑risk processing, will keep Records of Processing (GDPR Art. 30), and will apply AI Act requirements for risk management, data governance, and transparency. Annual audits will be performed by our DPO and AI Compliance Officer.\n\nLinks: [GDPR Art. 35](${LINKS.gdpr35}), [GDPR Art. 30](${LINKS.gdpr30}), [AI Act](${LINKS.aiAct}).`,
        category: 'Deployment'
      },
      {
        question: 'Who is liable if the system is misused or regulatory breaches occur?',
        answer: `Liability will be defined by controller/processor arrangements (GDPR Art. 26) and contractual terms. Each party will be responsible for its own data and actions. In line with the 2024 Product Liability Directive, we will maintain audit records and insurance coverage to support accountability and redress.\n\nLinks: [GDPR Art. 26](${LINKS.gdpr25}), [Product Liability Directive 2024/2853](${LINKS.productLiability2024}).`,
        category: 'Accounts'
      },
      {
        question: 'How do you handle export control, sector‑specific, or antitrust rules?',
        answer: `We will screen all projects against EU Dual‑Use Regulation 2021/821 and sectoral frameworks (e.g., EBA/EMA). Collaborations will be structured to avoid information sharing that could breach TFEU Arts. 101–102. Sensitive datasets will be processed only in isolated EU nodes with full logging.\n\nLinks: [Dual‑Use 2021/821](${LINKS.dualUse}), [TFEU 101](${LINKS.tfeu101}), [TFEU 102](${LINKS.tfeu102}).`,
        category: 'Deployment'
      },
      {
        question: 'Are audit trails and contracts maintained for legal defensibility?',
        answer: `Yes. All model runs and access logs will be retained for up to 10 years, and SLAs/DPAs will define rights, responsibilities, and audit clauses.\n\nLinks: [AI Act – record keeping](${LINKS.aiAct}).`,
        category: 'Accounts'
      }
    ]
  },
  {
    title: 'Cross‑Cutting Concerns',
    items: [
      {
        question: 'How do you control cloud cost and resource usage?',
        answer: `We will apply transparent usage‑based billing and resource caps per organization. Monitoring dashboards will help avoid unexpected cost spikes and will support sustainable AI operation in line with EU Green Digital Principles.\n\nLinks: [Green Digital Principles](${LINKS.greenDigital}).`,
        category: 'Getting Started'
      },
      {
        question: 'How do you ensure data quality and trust in partners’ datasets?',
        answer: `All participants will be required to meet our Data Quality Policy aligned with the AI Act’s data and data‑governance requirements. Datasets will be checked for accuracy, completeness, and lawful provenance before training or use.\n\nLinks: [AI Act](${LINKS.aiAct}).`,
        category: 'Deployment'
      }
    ]
  }
];

export default function FAQPage() {
  const { t } = useLanguage();
  const [query, setQuery] = useState('');
  const [activeCategory, setActiveCategory] = useState<'All' | FAQItem['category']>('All');
  const [openKey, setOpenKey] = useState<string | null>(null);
  const [openAll, setOpenAll] = useState<boolean>(false);

  const allFaqs: FAQItem[] = useMemo(() => SECTIONS.flatMap(s => s.items), []);

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    return allFaqs.filter((f) => {
      const matchesCategory = activeCategory === 'All' || f.category === activeCategory;
      const matchesQuery = !q || f.question.toLowerCase().includes(q) || f.answer.toLowerCase().includes(q);
      return matchesCategory && matchesQuery;
    });
  }, [query, activeCategory, allFaqs]);

  // Group filtered items by original section order
  const grouped = useMemo(() => {
    const q = query.trim().toLowerCase();
    return SECTIONS.map((s) => ({
      title: s.title,
      id: s.title.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
      items: s.items.filter((f) => {
        const matchesCategory = activeCategory === 'All' || f.category === activeCategory;
        const matchesQuery = !q || f.question.toLowerCase().includes(q) || f.answer.toLowerCase().includes(q);
        return matchesCategory && matchesQuery;
      })
    })).filter((s) => s.items.length > 0);
  }, [query, activeCategory]);

  return (
    <div className="min-h-screen bg-gradient-to-b from-surface/40 via-surface/20 to-transparent">
      {/* Hero */}
      <div className="relative overflow-hidden">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
          <div className="flex items-center gap-3 mb-2">
            <div className="w-10 h-10 rounded-xl bg-primary/15 flex items-center justify-center">
              <BookOpen className="w-5 h-5 text-primary" />
            </div>
            <div>
              <h1 className="text-3xl sm:text-4xl font-bold text-text-primary">{t('faq.title')}</h1>
              <p className="text-text-secondary mt-1">{t('faq.subtitle')}</p>
              <p className="text-[12px] mt-2 inline-block rounded-md border border-yellow-400/30 bg-yellow-500/10 px-2 py-1 text-yellow-300">
                Prototype notice: answers describe how the system will operate.
              </p>
            </div>
          </div>

          {/* Search + Categories */}
          <div className="mt-6 grid grid-cols-1 lg:grid-cols-3 gap-4">
            <Card className="p-4 lg:col-span-2">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 w-4 h-4" />
                <Input
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                  placeholder={t('faq.search')}
                  className="pl-9"
                />
              </div>
            </Card>
            <Card className="p-3 flex items-center gap-3">
              <Button
                variant={activeCategory === 'All' ? 'primary' : 'outline'}
                size="sm"
                onClick={() => setActiveCategory('All')}
                className="mr-1"
              >All</Button>
              {(['Getting Started','Deployment','Accounts'] as const).map((c) => (
                <Button
                  key={c}
                  variant={activeCategory === c ? 'primary' : 'outline'}
                  size="sm"
                  onClick={() => setActiveCategory(c)}
                >{c}</Button>
              ))}
            </Card>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pb-16">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* FAQs (grouped) */}
          <div className="lg:col-span-2 space-y-6">
            <div className="flex items-center gap-2">
              <Button variant="outline" size="sm" onClick={() => setOpenAll(true)}>Expand all</Button>
              <Button variant="outline" size="sm" onClick={() => { setOpenAll(false); setOpenKey(null); }}>Collapse all</Button>
            </div>
            {grouped.map((section) => (
              <div key={section.id} id={section.id} className="scroll-mt-24">
                <h2 className="text-xl font-semibold text-text-primary mb-2">{section.title}</h2>
                <div className="space-y-3">
                  {section.items.map((item, index) => {
                    const key = `${section.id}-${index}`;
                    const isOpen = openAll || openKey === key;
                    return (
                      <Card key={key} className="p-4 hover:shadow-glow transition-shadow">
                        <button
                          onClick={() => setOpenKey(isOpen ? null : key)}
                          className="w-full flex items-center justify-between text-left"
                        >
                          <div className="flex items-center gap-2">
                            <BookOpen className="w-4 h-4 text-primary" />
                            <span className="font-medium text-text-primary">{item.question}</span>
                          </div>
                          {isOpen ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                        </button>
                        {isOpen && (
                          <div className="mt-3 text-sm text-text-secondary leading-relaxed">
                            <div className="mb-2 inline-flex rounded-full px-2 py-0.5 text-[11px] border border-neutral-300 text-neutral-600">
                              {item.category}
                            </div>
                            <div className="space-y-3">
                              {item.answer.split('\n\n').map((p, i) => (
                                <p key={i} className="whitespace-pre-wrap">
                                  {p.split(/(\[[^\]]+\]\([^\)]+\))/g).map((chunk, j) => {
                                    const match = chunk.match(/^\[([^\]]+)\]\(([^\)]+)\)$/);
                                    if (match) {
                                      const [, label, href] = match;
                                      return (
                                        <a key={`${i}-${j}`} href={href} target="_blank" rel="noreferrer" className="text-primary hover:underline inline-flex items-center gap-1">
                                          <LinkIcon className="w-3 h-3" /> {label}
                                        </a>
                                      );
                                    }
                                    return <span key={`${i}-${j}`}>{chunk}</span>;
                                  })}
                                </p>
                              ))}
                            </div>
                          </div>
                        )}
                      </Card>
                    );
                  })}
                </div>
              </div>
            ))}

            {filtered.length === 0 && (
              <Card className="p-8 text-center text-text-secondary">No results. Try another keyword.</Card>
            )}
          </div>

          {/* Table of contents and Contact */}
          <div className="space-y-4">
            <Card className="p-5 sticky top-24">
              <h3 className="font-semibold text-text-primary mb-3">On this page</h3>
              <div className="space-y-2 text-sm">
                {SECTIONS.map((s) => {
                  const id = s.title.toLowerCase().replace(/[^a-z0-9]+/g, '-');
                  return (
                    <a key={s.title} href={`#${id}`} className="block text-text-secondary hover:text-text-primary">• {s.title}</a>
                  );
                })}
              </div>
            </Card>
            <Card className="p-5">
              <h3 className="font-semibold text-text-primary mb-2">Need more help?</h3>
              <p className="text-sm text-text-secondary mb-4">Our quick-start and help pages cover common tasks and deployment steps.</p>
              <div className="flex gap-2">
                <a href="/features">
                  <Button variant="outline" size="sm" className="flex items-center gap-2"><MessageCircle className="w-4 h-4"/> Explore Features</Button>
                </a>
              </div>
            </Card>
          </div>
        </div>
      </div>
      {/* Pre-implementation banner (bottom) */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="mt-6 rounded-xl border border-yellow-300/30 bg-yellow-50 dark:bg-yellow-900/20 px-5 py-4 text-center shadow-sm">
          <p className="font-semibold text-yellow-800 dark:text-yellow-200">
            <AlertCircle className="inline w-4 h-4 mr-2 align-[-2px]" />
            Pre‑implementation Note — These FAQs represent the questions and requirements we will validate before building the production system.
          </p>
          <p className="text-sm mt-1 text-yellow-700 dark:text-yellow-200/90">
            We will incorporate feedback from legal counsel, data protection officers, and EU digital regulation experts (GDPR, AI Act, NIS 2), and will refine this page accordingly.
          </p>
        </div>
      </div>
    </div>
  );
}


