grafana:
  enabled: true
  persistence:
    enabled: false
  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s/"
prometheus:
  prometheusSpec:
    retention: 15d
    retentionSize: 10GiB
alertmanager:
  enabled: true


