server:
  ha:
    enabled: false
  dataStorage:
    enabled: false
  auditStorage:
    enabled: false
  extraEnvironmentVars:
    VAULT_SEAL_TYPE: gcpckms
    GOOGLE_REGION: europe-north1
  extraVolumes:
    - type: secret
      name: vault-gcpkms
  standalone:
    enabled: true
    config: |
      ui = true
      listener "tcp" {
        address       = "0.0.0.0:8200"
        tls_disable   = 1
      }
      seal "gcpckms" {
        project     = "${var.project_id}"
        region      = "${var.region}"
        key_ring    = "ai-sandbox-keyring"
        crypto_key  = "vault-auto-unseal"
      }
      storage "file" { path = "/vault/data" }


