"""current_schema

Revision ID: 49901d61411d
Revises: 
Create Date: 2025-11-18 15:34:46.058735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '49901d61411d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projectcontextrecord')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projectcontextrecord',
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('version', sa.INTEGER(), nullable=False),
    sa.Column('context_json', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    # ### end Alembic commands ###
