"""current_schema

Revision ID: 631f32926fe3
Revises: 
Create Date: 2025-11-10 20:47:18.939908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '631f32926fe3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projectcontextrecord_project_id'), table_name='projectcontextrecord')
    op.drop_index(op.f('ix_projectcontextrecord_version'), table_name='projectcontextrecord')
    op.drop_table('projectcontextrecord')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projectcontextrecord',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('version', sa.INTEGER(), nullable=False),
    sa.Column('payload', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projectcontextrecord_version'), 'projectcontextrecord', ['version'], unique=False)
    op.create_index(op.f('ix_projectcontextrecord_project_id'), 'projectcontextrecord', ['project_id'], unique=False)
    # ### end Alembic commands ###
