'use client';

import React, { useState } from 'react';
import { Card } from '@/components/Card';
import { Button } from '@/components/Button';
import { Badge } from '@/components/Badge';
import { 
  Upload, 
  Search, 
  Brain, 
  Download, 
  Play, 
  CheckCircle, 
  MessageSquare,
  Database,
  Zap,
  Settings,
  FileText
} from 'lucide-react';

interface RAGSystemServiceProps {
  service: any;
}

export default function RAGSystemService({ service }: RAGSystemServiceProps) {
  const [currentStep, setCurrentStep] = useState(1);
  const [documents, setDocuments] = useState<File[]>([]);
  const [ragConfig, setRAGConfig] = useState({
    embeddingModel: 'text-embedding-ada-002',
    chunkSize: 1000,
    chunkOverlap: 200,
    retrievalMethod: 'similarity',
    llmModel: 'gpt-3.5-turbo'
  });
  const [query, setQuery] = useState('');
  const [isProcessing, setIsProcessing] = useState(false);
  const [results, setResults] = useState<any>(null);

  const handleFileUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(event.target.files || []);
    setDocuments(prev => [...prev, ...files]);
  };

  const removeDocument = (index: number) => {
    setDocuments(prev => prev.filter((_, i) => i !== index));
  };

  const buildRAGSystem = async () => {
    setIsProcessing(true);
    setCurrentStep(4);

    // Simulate RAG system building
    setTimeout(() => {
      setResults({
        documentsProcessed: documents.length,
        chunksCreated: documents.length * 15,
        embeddingsGenerated: documents.length * 15,
        indexSize: '2.4 MB',
        buildTime: '1m 23s',
        vectorDatabase: 'Pinecone (simulated)',
        retrievalAccuracy: 94.2,
        systemReady: true
      });
      setIsProcessing(false);
      setCurrentStep(5);
    }, 2500);
  };

  const queryRAGSystem = async () => {
    if (!query.trim()) return;
    
    setIsProcessing(true);
    
    // Simulate RAG query
    setTimeout(() => {
      const mockResponse = {
        query: query,
        answer: `Based on your uploaded documents, here's what I found about "${query}":

This is a comprehensive answer generated by combining information from multiple sources in your document collection. The RAG system has retrieved the most relevant chunks and synthesized them into this response.

Key points:
• Information retrieved from ${Math.floor(Math.random() * 3) + 1} different documents
• Confidence score: ${(Math.random() * 20 + 80).toFixed(1)}%
• Sources include technical documentation and reference materials`,
        sources: [
          { document: documents[0]?.name || 'Document 1', chunk: 'Page 2, Paragraph 3', relevance: 0.92 },
          { document: documents[1]?.name || 'Document 2', chunk: 'Page 5, Section 2.1', relevance: 0.87 },
          { document: documents[2]?.name || 'Document 3', chunk: 'Page 1, Introduction', relevance: 0.84 }
        ].slice(0, documents.length),
        processingTime: '1.2s',
        tokensUsed: 1247
      };
      
      setResults((prev: any) => ({ ...prev, lastQuery: mockResponse }));
      setIsProcessing(false);
    }, 1200);
  };

  const resetWorkflow = () => {
    setCurrentStep(1);
    setDocuments([]);
    setQuery('');
    setResults(null);
  };

  return (
    <div className="space-y-6">
      {/* Step 1: Document Upload */}
      {currentStep === 1 && (
        <Card className="p-6">
          <h2 className="text-xl font-semibold text-white mb-4">Upload Knowledge Base Documents</h2>
          <div className="space-y-4">
            <div className="border-2 border-dashed border-slate-600 rounded-lg p-8 text-center">
              <Upload className="w-12 h-12 text-slate-400 mx-auto mb-4" />
              <h3 className="text-lg font-medium text-white mb-2">
                Upload documents for your RAG system
              </h3>
              <p className="text-slate-400 mb-4">
                Supported: PDF, DOC, TXT, MD (max 10MB each)
              </p>
              <input
                type="file"
                accept=".pdf,.doc,.docx,.txt,.md"
                multiple
                onChange={handleFileUpload}
                className="hidden"
                id="document-upload"
              />
              <label htmlFor="document-upload">
                <Button className="btn-primary cursor-pointer">
                  Choose Documents
                </Button>
              </label>
            </div>
            
            {documents.length > 0 && (
              <div className="space-y-2">
                <h4 className="text-white font-medium">Uploaded Documents ({documents.length}):</h4>
                {documents.map((doc, index) => (
                  <div key={index} className="flex items-center justify-between p-3 bg-slate-700 rounded-lg">
                    <div className="flex items-center gap-2">
                      <FileText className="w-4 h-4 text-blue-400" />
                      <span className="text-white">{doc.name}</span>
                      <span className="text-slate-400 text-sm">
                        ({(doc.size / 1024 / 1024).toFixed(2)} MB)
                      </span>
                    </div>
                    <Button 
                      size="sm" 
                      variant="outline" 
                      onClick={() => removeDocument(index)}
                      className="text-red-400 hover:text-red-300"
                    >
                      Remove
                    </Button>
                  </div>
                ))}
              </div>
            )}

            <div className="flex justify-end">
              <Button 
                onClick={() => setCurrentStep(2)}
                disabled={documents.length === 0}
                className="btn-primary"
              >
                Next: Configure RAG System
              </Button>
            </div>
          </div>
        </Card>
      )}

      {/* Step 2: RAG Configuration */}
      {currentStep === 2 && (
        <Card className="p-6">
          <h2 className="text-xl font-semibold text-white mb-4">Configure RAG System</h2>
          <div className="space-y-6">
            <div>
              <label className="block text-sm font-medium text-white mb-2">Embedding Model</label>
              <select 
                value={ragConfig.embeddingModel}
                onChange={(e) => setRAGConfig({...ragConfig, embeddingModel: e.target.value})}
                className="w-full p-2 bg-slate-800 border border-slate-700 rounded text-white"
              >
                <option value="text-embedding-ada-002">OpenAI Ada 002 (Best quality)</option>
                <option value="sentence-transformers">Sentence Transformers (Open source)</option>
                <option value="cohere-embed">Cohere Embed (Fast)</option>
              </select>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-white mb-2">Chunk Size</label>
                <select 
                  value={ragConfig.chunkSize}
                  onChange={(e) => setRAGConfig({...ragConfig, chunkSize: parseInt(e.target.value)})}
                  className="w-full p-2 bg-slate-800 border border-slate-700 rounded text-white"
                >
                  <option value={500}>500 tokens (Small)</option>
                  <option value={1000}>1000 tokens (Medium)</option>
                  <option value={1500}>1500 tokens (Large)</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-white mb-2">Chunk Overlap</label>
                <select 
                  value={ragConfig.chunkOverlap}
                  onChange={(e) => setRAGConfig({...ragConfig, chunkOverlap: parseInt(e.target.value)})}
                  className="w-full p-2 bg-slate-800 border border-slate-700 rounded text-white"
                >
                  <option value={100}>100 tokens</option>
                  <option value={200}>200 tokens</option>
                  <option value={300}>300 tokens</option>
                </select>
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-white mb-2">LLM Model</label>
              <select 
                value={ragConfig.llmModel}
                onChange={(e) => setRAGConfig({...ragConfig, llmModel: e.target.value})}
                className="w-full p-2 bg-slate-800 border border-slate-700 rounded text-white"
              >
                <option value="gpt-3.5-turbo">GPT-3.5 Turbo (Fast & Cost-effective)</option>
                <option value="gpt-4">GPT-4 (Best Quality)</option>
                <option value="gpt-4-turbo">GPT-4 Turbo (Large Context)</option>
              </select>
            </div>
          </div>

          <div className="flex justify-between mt-6">
            <Button onClick={() => setCurrentStep(1)} variant="outline">
              Back
            </Button>
            <Button 
              onClick={() => setCurrentStep(3)}
              className="btn-primary"
            >
              Next: Build RAG System
            </Button>
          </div>
        </Card>
      )}

      {/* Step 3: Build System */}
      {currentStep === 3 && (
        <Card className="p-6">
          <h2 className="text-xl font-semibold text-white mb-4">Build RAG System</h2>
          <div className="space-y-4">
            <div className="bg-slate-700 rounded-lg p-4 space-y-3">
              <div className="flex items-center gap-2 text-white">
                <FileText className="w-5 h-5" />
                <span className="font-medium">Documents:</span> {documents.length} files
              </div>
              <div className="flex items-center gap-2 text-white">
                <Brain className="w-5 h-5" />
                <span className="font-medium">Embedding Model:</span> {ragConfig.embeddingModel}
              </div>
              <div className="flex items-center gap-2 text-white">
                <Settings className="w-5 h-5" />
                <span className="font-medium">Chunk Size:</span> {ragConfig.chunkSize} tokens
              </div>
              <div className="flex items-center gap-2 text-white">
                <MessageSquare className="w-5 h-5" />
                <span className="font-medium">LLM:</span> {ragConfig.llmModel}
              </div>
            </div>

            <div className="bg-blue-500/10 border border-blue-500/20 rounded-lg p-4">
              <h4 className="text-blue-400 font-medium mb-2">RAG Pipeline:</h4>
              <div className="text-sm text-blue-300 space-y-1">
                <p>1. Document parsing and text extraction</p>
                <p>2. Intelligent chunking with overlap</p>
                <p>3. Generate embeddings using {ragConfig.embeddingModel}</p>
                <p>4. Build vector database index</p>
                <p>5. Configure retrieval and generation pipeline</p>
                <p>6. Test system with sample queries</p>
              </div>
            </div>
          </div>

          <div className="flex justify-between mt-6">
            <Button onClick={() => setCurrentStep(2)} variant="outline">
              Back
            </Button>
            <Button 
              onClick={buildRAGSystem}
              className="btn-primary flex items-center gap-2"
            >
              <Play className="w-4 h-4" />
              Build RAG System
            </Button>
          </div>
        </Card>
      )}

      {/* Step 4: Building */}
      {currentStep === 4 && (
        <Card className="p-6">
          <h2 className="text-xl font-semibold text-white mb-4">Building RAG System</h2>
          <div className="space-y-6">
            <div className="text-center">
              <div className="w-16 h-16 bg-primary/20 rounded-full flex items-center justify-center mx-auto mb-4">
                <Brain className="w-8 h-8 text-primary animate-pulse" />
              </div>
              <h3 className="text-lg font-medium text-white mb-2">Processing Documents</h3>
              <p className="text-slate-400">
                Creating embeddings and building vector database
              </p>
            </div>

            <div className="space-y-2 text-sm text-slate-300">
              <div className="flex items-center gap-2">
                <CheckCircle className="w-4 h-4 text-green-500" />
                <span>Documents parsed and chunked</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle className="w-4 h-4 text-green-500" />
                <span>Embeddings generated</span>
              </div>
              <div className="flex items-center gap-2">
                <div className="w-4 h-4 border-2 border-primary border-t-transparent rounded-full animate-spin"></div>
                <span>Building vector index...</span>
              </div>
            </div>
          </div>
        </Card>
      )}

      {/* Step 5: RAG System Ready */}
      {currentStep === 5 && results && (
        <div className="space-y-6">
          <Card className="p-6">
            <div className="flex items-center gap-2 mb-6">
              <CheckCircle className="w-6 h-6 text-green-500" />
              <h2 className="text-xl font-semibold text-white">RAG System Ready!</h2>
            </div>

            {/* System Stats */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
              <div className="text-center p-4 bg-green-500/10 border border-green-500/20 rounded-lg">
                <div className="text-2xl font-bold text-green-400">{results.documentsProcessed}</div>
                <div className="text-sm text-green-300">Documents</div>
              </div>
              <div className="text-center p-4 bg-blue-500/10 border border-blue-500/20 rounded-lg">
                <div className="text-2xl font-bold text-blue-400">{results.chunksCreated}</div>
                <div className="text-sm text-blue-300">Chunks</div>
              </div>
              <div className="text-center p-4 bg-purple-500/10 border border-purple-500/20 rounded-lg">
                <div className="text-2xl font-bold text-purple-400">{results.embeddingsGenerated}</div>
                <div className="text-sm text-purple-300">Embeddings</div>
              </div>
              <div className="text-center p-4 bg-yellow-500/10 border border-yellow-500/20 rounded-lg">
                <div className="text-2xl font-bold text-yellow-400">{results.retrievalAccuracy}%</div>
                <div className="text-sm text-yellow-300">Accuracy</div>
              </div>
            </div>

            {/* Query Interface */}
            <Card className="p-4 bg-slate-700 border-slate-600 mb-6">
              <h4 className="text-lg font-semibold text-white mb-4">Ask Your Documents</h4>
              <div className="space-y-4">
                <textarea
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                  placeholder="Ask a question about your uploaded documents..."
                  className="w-full h-24 p-3 bg-slate-800 border border-slate-700 rounded-lg text-white placeholder-slate-400"
                />
                <Button 
                  onClick={queryRAGSystem}
                  disabled={!query.trim() || isProcessing}
                  className="btn-primary flex items-center gap-2"
                >
                  {isProcessing ? (
                    <>
                      <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                      Processing...
                    </>
                  ) : (
                    <>
                      <Search className="w-4 h-4" />
                      Ask Question
                    </>
                  )}
                </Button>
              </div>
            </Card>

            {/* Query Results */}
            {results.lastQuery && (
              <Card className="p-4 bg-slate-700 border-slate-600 mb-6">
                <h4 className="text-lg font-semibold text-white mb-4">RAG Response</h4>
                <div className="space-y-4">
                  <div className="bg-slate-800 rounded-lg p-4">
                    <h5 className="text-blue-400 font-medium mb-2">Question:</h5>
                    <p className="text-slate-300 mb-4">{results.lastQuery.query}</p>
                    
                    <h5 className="text-green-400 font-medium mb-2">Answer:</h5>
                    <p className="text-slate-300 whitespace-pre-line">{results.lastQuery.answer}</p>
                  </div>

                  <div className="bg-slate-800 rounded-lg p-4">
                    <h5 className="text-purple-400 font-medium mb-2">Sources:</h5>
                    <div className="space-y-2">
                      {results.lastQuery.sources.map((source: any, index: number) => (
                        <div key={index} className="flex items-center justify-between p-2 bg-slate-700 rounded">
                          <div className="flex items-center gap-2">
                            <FileText className="w-4 h-4 text-blue-400" />
                            <span className="text-slate-300">{source.document}</span>
                            <span className="text-slate-500 text-sm">({source.chunk})</span>
                          </div>
                          <Badge variant="secondary">{(source.relevance * 100).toFixed(0)}%</Badge>
                        </div>
                      ))}
                    </div>
                  </div>

                  <div className="text-xs text-slate-500">
                    Processing time: {results.lastQuery.processingTime} | 
                    Tokens used: {results.lastQuery.tokensUsed}
                  </div>
                </div>
              </Card>
            )}

            <div className="flex justify-between items-center">
              <Button onClick={resetWorkflow} variant="outline" className="flex items-center gap-2">
                <Upload className="w-4 h-4" />
                Build New RAG System
              </Button>
              <div className="flex gap-2">
                <Button className="btn-secondary flex items-center gap-2">
                  <Download className="w-4 h-4" />
                  Export Configuration
                </Button>
                <Button className="btn-primary flex items-center gap-2">
                  <Database className="w-4 h-4" />
                  Deploy to Production
                </Button>
              </div>
            </div>
          </Card>
        </div>
      )}
    </div>
  );
}
