'use client';

import React, { useState, useEffect } from 'react';
import { Card } from '@/components/Card';
import { Button } from '@/components/Button';
import { Badge } from '@/components/Badge';
import { 
  BarChart3, 
  Download, 
  Share2, 
  Filter, 
  Calendar,
  TrendingUp,
  Target,
  Users,
  Clock,
  CheckCircle,
  AlertTriangle,
  FileText,
  Database,
  Activity,
  Zap
} from 'lucide-react';
import { LineChart, Line, AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell, BarChart, Bar, Legend } from 'recharts';

interface ResultsDashboardServiceProps {
  service: any;
}

export default function ResultsDashboardService({ service }: ResultsDashboardServiceProps) {
  const [selectedProject, setSelectedProject] = useState('');
  const [timeRange, setTimeRange] = useState('30d');
  const [selectedMetrics, setSelectedMetrics] = useState<string[]>(['accuracy', 'performance', 'usage']);
  const [isGenerating, setIsGenerating] = useState(false);
  const [dashboardData, setDashboardData] = useState<any>(null);

  const projects = [
    { id: 'proj-1', name: 'AI Healthcare Diagnostics', status: 'active', accuracy: 94.2 },
    { id: 'proj-2', name: 'NLP Sentiment Analysis', status: 'completed', accuracy: 89.7 },
    { id: 'proj-3', name: 'Computer Vision Object Detection', status: 'active', accuracy: 91.5 },
    { id: 'proj-4', name: 'Recommendation Engine', status: 'testing', accuracy: 87.3 }
  ];

  const performanceData = [
    { time: '00:00', accuracy: 89.2, latency: 120, throughput: 45 },
    { time: '04:00', accuracy: 91.5, latency: 98, throughput: 52 },
    { time: '08:00', accuracy: 94.1, latency: 85, throughput: 68 },
    { time: '12:00', accuracy: 92.8, latency: 92, throughput: 61 },
    { time: '16:00', accuracy: 93.5, latency: 88, throughput: 58 },
    { time: '20:00', accuracy: 90.7, latency: 105, throughput: 49 }
  ];

  const usageData = [
    { name: 'Text Analysis', value: 35, color: '#3b82f6' },
    { name: 'Computer Vision', value: 28, color: '#10b981' },
    { name: 'NLP Processing', value: 22, color: '#f59e0b' },
    { name: 'Recommendation', value: 15, color: '#ef4444' }
  ];

  const modelPerformanceData = [
    { model: 'BERT-base', accuracy: 94.2, speed: 120, cost: 0.02 },
    { model: 'GPT-3.5', accuracy: 91.8, speed: 85, cost: 0.05 },
    { model: 'ResNet-50', accuracy: 89.5, speed: 95, cost: 0.03 },
    { model: 'YOLO-v8', accuracy: 92.1, speed: 110, cost: 0.04 }
  ];

  const generateDashboard = async () => {
    setIsGenerating(true);
    
    // Simulate dashboard generation
    setTimeout(() => {
      setDashboardData({
        totalRequests: 15420,
        averageAccuracy: 92.3,
        totalCost: 1247.50,
        activeModels: 8,
        lastUpdated: new Date().toISOString(),
        topPerformingModel: 'BERT-base',
        costSavings: 23.5,
        complianceScore: 98.2
      });
      setIsGenerating(false);
    }, 2000);
  };

  const exportReport = () => {
    const reportContent = `
GPT-Lab’s AI Services - Results Dashboard Report
==========================================

Generated: ${new Date().toLocaleString()}
Project: ${projects.find(p => p.id === selectedProject)?.name || 'All Projects'}

KEY METRICS
===========
Total Requests: ${dashboardData?.totalRequests || 'N/A'}
Average Accuracy: ${dashboardData?.averageAccuracy || 'N/A'}%
Total Cost: €${dashboardData?.totalCost || 'N/A'}
Active Models: ${dashboardData?.activeModels || 'N/A'}
Compliance Score: ${dashboardData?.complianceScore || 'N/A'}%

TOP PERFORMING MODEL
===================
Model: ${dashboardData?.topPerformingModel || 'N/A'}
Cost Savings: ${dashboardData?.costSavings || 'N/A'}%

PERFORMANCE TRENDS
==================
• Accuracy has improved by 12% over the last 30 days
• Latency reduced by 18% through optimization
• Cost efficiency improved by 23.5%
• Compliance maintained at 98.2%

RECOMMENDATIONS
===============
1. Scale up BERT-base model usage (best performance/cost ratio)
2. Implement caching for frequently requested models
3. Consider model quantization for 15% cost reduction
4. Schedule maintenance during low-usage hours

---
Generated by GPT-Lab’s Sandbox AI Services Platform
    `;

    const blob = new Blob([reportContent], { type: 'text/plain;charset=utf-8' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `AI-Services-Dashboard-${new Date().toISOString().split('T')[0]}.txt`;
    link.click();
    window.URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-white">Results Dashboard & Reports</h2>
          <p className="text-gray-400">Comprehensive analytics and reporting for AI services</p>
        </div>
        <div className="flex space-x-3">
          <Button 
            onClick={generateDashboard}
            disabled={isGenerating}
            className="bg-blue-600 hover:bg-blue-700"
          >
            {isGenerating ? (
              <>
                <Activity className="w-4 h-4 mr-2 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <BarChart3 className="w-4 h-4 mr-2" />
                Generate Dashboard
              </>
            )}
          </Button>
          <Button 
            onClick={exportReport}
            className="bg-green-600 hover:bg-green-700"
          >
            <Download className="w-4 h-4 mr-2" />
            Export Report
          </Button>
        </div>
      </div>

      {/* Configuration Panel */}
      <Card className="p-6">
        <h3 className="text-lg font-semibold text-white mb-4">Dashboard Configuration</h3>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-300 mb-2">Project</label>
            <select 
              value={selectedProject}
              onChange={(e) => setSelectedProject(e.target.value)}
              className="w-full bg-gray-700 border border-gray-600 rounded-lg px-3 py-2 text-white"
            >
              <option value="">All Projects</option>
              {projects.map(project => (
                <option key={project.id} value={project.id}>{project.name}</option>
              ))}
            </select>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-300 mb-2">Time Range</label>
            <select 
              value={timeRange}
              onChange={(e) => setTimeRange(e.target.value)}
              className="w-full bg-gray-700 border border-gray-600 rounded-lg px-3 py-2 text-white"
            >
              <option value="7d">Last 7 days</option>
              <option value="30d">Last 30 days</option>
              <option value="90d">Last 90 days</option>
              <option value="1y">Last year</option>
            </select>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-300 mb-2">Metrics</label>
            <div className="flex flex-wrap gap-2">
              {['accuracy', 'performance', 'usage', 'cost'].map(metric => (
                <button
                  key={metric}
                  onClick={() => setSelectedMetrics(prev => 
                    prev.includes(metric) 
                      ? prev.filter(m => m !== metric)
                      : [...prev, metric]
                  )}
                  className={`px-3 py-1 rounded-full text-sm ${
                    selectedMetrics.includes(metric)
                      ? 'bg-blue-600 text-white'
                      : 'bg-gray-600 text-gray-300 hover:bg-gray-500'
                  }`}
                >
                  {metric}
                </button>
              ))}
            </div>
          </div>
        </div>
      </Card>

      {/* Dashboard Results */}
      {dashboardData && (
        <div className="space-y-6">
          {/* Key Metrics Cards */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            <Card className="p-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-gray-400 text-sm">Total Requests</p>
                  <p className="text-2xl font-bold text-white">{dashboardData.totalRequests.toLocaleString()}</p>
                </div>
                <Database className="w-8 h-8 text-blue-500" />
              </div>
            </Card>
            <Card className="p-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-gray-400 text-sm">Average Accuracy</p>
                  <p className="text-2xl font-bold text-white">{dashboardData.averageAccuracy}%</p>
                </div>
                <Target className="w-8 h-8 text-green-500" />
              </div>
            </Card>
            <Card className="p-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-gray-400 text-sm">Total Cost</p>
                  <p className="text-2xl font-bold text-white">€{dashboardData.totalCost}</p>
                </div>
                <TrendingUp className="w-8 h-8 text-yellow-500" />
              </div>
            </Card>
            <Card className="p-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-gray-400 text-sm">Compliance Score</p>
                  <p className="text-2xl font-bold text-white">{dashboardData.complianceScore}%</p>
                </div>
                <CheckCircle className="w-8 h-8 text-purple-500" />
              </div>
            </Card>
          </div>

          {/* Charts */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Performance Over Time */}
            <Card className="p-6">
              <h3 className="text-lg font-semibold text-white mb-4">Performance Over Time</h3>
              <ResponsiveContainer width="100%" height={300}>
                <LineChart data={performanceData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#374151" />
                  <XAxis dataKey="time" stroke="#9ca3af" />
                  <YAxis stroke="#9ca3af" />
                  <Tooltip 
                    contentStyle={{ 
                      backgroundColor: '#1f2937', 
                      border: '1px solid #374151',
                      borderRadius: '8px'
                    }} 
                  />
                  <Line type="monotone" dataKey="accuracy" stroke="#3b82f6" strokeWidth={2} />
                  <Line type="monotone" dataKey="latency" stroke="#10b981" strokeWidth={2} />
                </LineChart>
              </ResponsiveContainer>
            </Card>

            {/* Service Usage Distribution */}
            <Card className="p-6">
              <h3 className="text-lg font-semibold text-white mb-4">Service Usage Distribution</h3>
              <ResponsiveContainer width="100%" height={300}>
                <PieChart>
                  <Pie
                    data={usageData}
                    cx="50%"
                    cy="50%"
                    outerRadius={80}
                    fill="#8884d8"
                    dataKey="value"
                    label={({ name, value }) => `${name}: ${value}%`}
                  >
                    {usageData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                  <Tooltip />
                  <Legend />
                </PieChart>
              </ResponsiveContainer>
            </Card>
          </div>

          {/* Model Performance Table */}
          <Card className="p-6">
            <h3 className="text-lg font-semibold text-white mb-4">Model Performance Comparison</h3>
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="border-b border-gray-600">
                    <th className="text-left py-3 px-4 text-gray-300">Model</th>
                    <th className="text-left py-3 px-4 text-gray-300">Accuracy</th>
                    <th className="text-left py-3 px-4 text-gray-300">Speed (ms)</th>
                    <th className="text-left py-3 px-4 text-gray-300">Cost/Request</th>
                    <th className="text-left py-3 px-4 text-gray-300">Status</th>
                  </tr>
                </thead>
                <tbody>
                  {modelPerformanceData.map((model, index) => (
                    <tr key={index} className="border-b border-gray-700">
                      <td className="py-3 px-4 text-white font-medium">{model.model}</td>
                      <td className="py-3 px-4 text-white">{model.accuracy}%</td>
                      <td className="py-3 px-4 text-white">{model.speed}ms</td>
                      <td className="py-3 px-4 text-white">€{model.cost}</td>
                      <td className="py-3 px-4">
                        <Badge variant="green">Active</Badge>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </Card>

          {/* Insights and Recommendations */}
          <Card className="p-6">
            <h3 className="text-lg font-semibold text-white mb-4">AI Insights & Recommendations</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <h4 className="font-semibold text-white mb-3 flex items-center">
                  <Zap className="w-5 h-5 mr-2 text-yellow-500" />
                  Performance Insights
                </h4>
                <ul className="space-y-2 text-gray-300">
                  <li>• BERT-base model shows best accuracy/cost ratio</li>
                  <li>• Peak usage occurs between 10:00-14:00</li>
                  <li>• 23.5% cost savings achieved through optimization</li>
                  <li>• Compliance score maintained at 98.2%</li>
                </ul>
              </div>
              <div>
                <h4 className="font-semibold text-white mb-3 flex items-center">
                  <Target className="w-5 h-5 mr-2 text-blue-500" />
                  Recommendations
                </h4>
                <ul className="space-y-2 text-gray-300">
                  <li>• Scale up BERT-base usage for cost efficiency</li>
                  <li>• Implement caching for 15% performance boost</li>
                  <li>• Schedule maintenance during low-usage hours</li>
                  <li>• Consider model quantization for further savings</li>
                </ul>
              </div>
            </div>
          </Card>
        </div>
      )}

      {/* Demo Notice */}
      <Card className="p-4 bg-yellow-900/20 border border-yellow-500/30">
        <div className="flex items-center">
          <AlertTriangle className="w-5 h-5 text-yellow-400 mr-3" />
          <p className="text-yellow-300 font-medium">Demo Version</p>
        </div>
        <p className="text-yellow-200 text-sm mt-1">
          This dashboard shows simulated data for demonstration purposes. In a production environment, 
          this would display real-time analytics from your AI services.
        </p>
      </Card>
    </div>
  );
}