apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: block-latest
spec:
  validationFailureAction: enforce
  background: true
  rules:
    - name: disallow-latest-tag
      match:
        any:
          - resources:
              kinds: [Pod]
      validate:
        message: "Using ':latest' image tag is not allowed."
        pattern:
          spec:
            containers:
              - image: '!*:latest'


