apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-limits
spec:
  validationFailureAction: enforce
  background: true
  rules:
    - name: validate-container-resources
      match:
        any:
          - resources:
              kinds: [Pod]
      validate:
        message: "Containers must have CPU and memory limits and requests set."
        pattern:
          spec:
            containers:
              - resources:
                  requests:
                    memory: "?*"
                    cpu: "?*"
                  limits:
                    memory: "?*"
                    cpu: "?*"


