apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-signed
spec:
  validationFailureAction: enforce
  background: true
  rules:
    - name: check-cosign
      match:
        any:
          - resources:
              kinds: [Pod]
      verifyImages:
        - imageReferences:
            - "ghcr.io/*/*"
          attestors:
            - entries:
                - keyless:
                    issuer: "https://token.actions.githubusercontent.com"
                    subject: "*"
          repository: "ghcr.io"

